### ISSUE TITLE
If an element is not present it is throwing NoMethodError rather than ElementMissingException

### ISSUE THREAD

**Issue by michaelanfield** [lvl-up/page_magic#58]
When defining an element with sub-elements and then trying to assert that the subelement is missing the error thrown is not ElementMissingException but NoMethodError.

```
base.element :product_purchase, css: '[data-finder=product-purchase-price]' do
  element :old_price, css: '.o-layout__item:nth-child(1) span'
end

it 'does not display an old price' do
  expect { subject.product_purchase.old_price }.to raise_error(PageMagic::ElementMissingException)
end
```

**Comment by lashd** [comment]
thanks for raising this one @michaelanfield. It looks like `PageMagic::Element#method_missing` needs to be changed.

we can assume that if a `PageMagic::ElementMissingException` is thrown from `PageMagic::ElementContext` [here](https://github.com/lvl-up/page_magic/blob/master/lib/page_magic/element_context.rb#L41), then we should let this bubble out. However if an element definition is [not found ](https://github.com/lvl-up/page_magic/blob/master/lib/page_magic/element_context.rb#L23) then we should throw a different type exception and this should allow the standard method missing handling take place.
