### ISSUE TITLE
Consider removing activesupport dependency

### ISSUE THREAD

**Issue by robisenberg** [lvl-up/page_magic#66]
Currently `activesupport` dependency is pinned to version `~>4`. This means it's impossible to use PageMagic with Rails 5 which has `activesupport` at `>= 5.0.0`.

I was going to see what broke by removing the `activesupport` dependency and try to update PageMagic to not depend on `activesupport` at all.

I'm not sure which parts of `activesupport` it's using. It's worth noting that, on removing it as a dependency, I got the same 7 test failures as in #65, which would suggest it may not even be needed??

Anyway, I'm blocked until I can get tests green again i.e. until I can get #65 resolved.

**Comment by lashd** [comment]
Hi @robisenberg, I have removed this dependency now. Thanks for raising
